### ISSUE TITLE
IDA 7.0 ponce

### ISSUE THREAD

**Issue by anic** [illera88/Ponce#88] opened 2018-03-04 10:18 UTC
when ida loads ponce plugin , the output window shows the following error:

LoadLibrary() error: 参数错误。
: can't load file

**Comment by mxmssh** [comment] 2018-03-06 04:11
Thank you for your interest in Ponce.

Could you specify more details: 
1. Do you use x32 or x64 IDA ?
2. What is your full path to IDA plugins folder ?
3. Do you use pre-compiled binaries or you compile Ponce by your own ?

**Comment by anic** [comment] 2018-03-06 07:21
Do you use x32 or x64 IDA ?
IDA 7.0，error in both x32 and x64 version

What is your full path to IDA plugins folder ?
E:\Program Files\IDA 7.0\

Do you use pre-compiled binaries or you compile Ponce by your own ?
using pre-compiled binaries

thx

**Comment by anic** [comment] 2018-03-06 07:23
yes

**Comment by mxmssh** [comment] 2018-03-06 07:27
Looks like a bug, did you follow instruction for IDA 7.0. installation (especially naming convention for the dll) ?

**Comment by mxmssh** [comment] 2018-03-06 07:28
We need details of your environment (OS version and etc.) to be able to reproduce and fix the bug.

**Comment by anic** [comment] 2018-03-06 07:51
oh, i just follow the instruction just put Ponce64.dll to the /plugin folder in IDA and make a line in config.cfg. I didn't recognized the naming convention.

I just rename Ponce64.dll to ponce64.dll, it works in IDAx64 version! but when i follow the example for the x64_fread_SAGE.exe, IDA crashes when i create execution snapshot....

by the way my os version is windows 7 professional service pack 1

**Comment by mxmssh** [comment] 2018-03-07 00:40
Ok, looks like we don't have anymore plugin loading problem but have a problem with execution snapshot. I am closing this issue and opening a new one which covers this problem.

**Closed by mxmssh** 2018-03-07 00:40 UTC
Labels: bug
